portal-frontend:
  enabled: true

portal-backend:
  enabled: true
  pgadmin4:
    nameOverride: "portal-backend-pgadmin4"
    # fullnameOverride: "portal-backend"
  postgresql:
    nameOverride: "portal-backend-postgresql"
    # fullnameOverride: "portal-backend"

bpdm:
  enabled: true

daps:
  enabled: true

centralidp:
  enabled: true
  keycloak:
    nameOverride: "centralidp-keycloak"
    # fullnameOverride: "centralidp"
    postgresql:
      enabled: true      
      primary:
        name: "primary"
      readReplicas:
        name: "read"
      nameOverride: "centralidp-postgresql"
      # fullnameOverride: "centralidp-postgresql"

sharedidp:
  enabled: true
  keycloak:
    nameOverride: "sharedidp-keycloak"
    # fullnameOverride: "sharedidp"
    postgresql:
      enabled: true
      nameOverride: "sharedidp-postgresql"
      primary:
        name: "primary"
      readReplicas:
        name: "read"
      # fullnameOverride: "sharedidp-postgresql"

managed-identity-wallets:
  enabled: true
  # vault is used if isLocal is true
  isLocal: true
  postgresql:
    nameOverride: "managed-identity-wallets-postgresql"
    # fullnameOverride: "managed-identity-wallets"
  # ingress can't be disabled
  certificate:
    host: "managed-identity-wallets.devsecops-testing.demo.catena-x.net"

sldt-registry:
  enabled: true
  postgresql:
    nameOverride: "sldt-registry-postgresql"
    # fullnameOverride: "sldt-registry"
  registry:
    # not set by default, but throws error
    idpClientId: ""
