apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.portalmigrations.name }}
  annotations:
    batch.kubernetes.io/job-tracking: "true"
spec:
  template:
    metadata:
      name: {{ .Values.portalmigrations.name }}
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Values.portalmigrations.name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.portalmigrations.image.name }}:{{ .Values.portalmigrations.image.portalmigrationstag | default .Chart.AppVersion }}"
        imagePullPolicy: "Always"
        ports:
        - containerPort: {{ .Values.portContainer }}
        volumeMounts:
        - name: secrets
          mountPath: /migrations/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ .Values.portalmigrations.secret.name }}
