apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.portalmaintenance.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  appsettings.json:  {{ .Values.portalmaintenance.secret.appsettings }}
