apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appmarketplace.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  appsettings.json: {{ .Values.appmarketplace.secret.appsettings }}
