apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.portService }}
    targetPort: {{ .Values.portContainer }}
  selector:
    app: {{ .Values.services.name }}
