apiVersion: v2
appVersion: 0.5.5
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.x.x
- condition: pgadmin4.enabled
  name: pgadmin4
  repository: https://helm.runix.net
  version: 1.11.x
description: Helm chart for Catena-X Portal backend
name: portal-backend
type: application
version: 0.5.5
