name: portal-backend
portContainer: 8080
portService: 8080
replicaCount: 1
securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: ["ALL"]

ingress:
  enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: secret-postgres-init
  secret:
    password: ""
    replicationPassword: ""
    initUserDbSql: ""
  architecture: replication
  audit:
    pgAuditLog: write, ddl
    logLinePrefix: "%m %u %d "
 
registration:
  name: registration-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_registration-service
    tag: int-v0.5.5
  secret:
    name: secret-registration
    appsettings: "'{}'"

administration:
  name: administration-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_administration-service
    tag: int-v0.5.5
  secret:
    name: secret-administration
    appsettings: "'{}'"

provisioning:
  name: provisioning-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_provisioning-service
    tag: int-v0.5.5
  secret:
    name: secret-provisioning
    appsettings: "'{}'"

appmarketplace:
  name: marketplace-app-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_marketplace-app-service
    tag: int-v0.5.5
  secret:
    name: secret-appmarketplace
    appsettings: "'{}'"

portalmigrations:
  name: portal-migrations
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_portal-migrations
    tag: int-v0.5.5
  secret:
    name: secret-portal-migrations
    appsettings: "'{}'"

portalmaintenance:
  name: portal-maintenance
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_maintenance-service
    tag: int-v0.5.5
  secret:
    name: secret-portal-maintenance
    appsettings: "'{}'"

notification:
  name: notification-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_notification-service
    tag: int-v0.5.5
  secret:
    name: secret-notification
    appsettings: "'{}'"

services:
  name: services-service
  image: 
    name: ghcr.io/catenax-ng/product-portal-backend_services-service
    tag: int-v0.5.5
  secret:
    name: secret-services
    appsettings: "'{}'"

pgadmin4:
  enabled: false
  ingress:
    enabled: false
